packages:
  - packages/*
  - playground/*

catalog:
  '@chainlink/contracts': ^1.5.0
  '@hairy/lnv': ^9.1.0

catalogMode: prefer

catalogs:
  cli:
    '@antfu/eslint-config': ^7.2.0
    '@antfu/ni': ^28.0.0
    eslint: ^9.39.2
    lint-staged: ^15.4.3
    simple-git-hooks: ^2.13.1
    typescript: ^5.9.3
  evm:
    '@nomicfoundation/hardhat-ignition': ^3.0.7
    '@nomicfoundation/hardhat-toolbox-viem': ^5.0.2
    forge-std: github:foundry-rs/forge-std#v1.9.4
    hardhat: ^3.1.9
    viem: ^2.46.3
  types:
    '@types/node': ^25.0.1

ignoreWorkspaceRootCheck: true

shellEmulator: true

trustPolicyExclude:
  - undici-types@6.21.0
